### ISSUE TITLE
libboost_ libraries during installation

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#101]
Currently the libboost_ libraries and include files are not moved from the $SHYFT_DEPENDENCIES_DIR during installation (e.g. python setup.py install). We should find a way that the required libraries are also included in the `data_files` list of the distutils setup.py instructions so that they are also moved into a standard installation location (or install location of a conda env).

**Comment by sigbjorn** [comment]
This is done for the win-distro, - for the linux distro it's quite straight forward, just need to check  what is the most common thing to do, - add it as external dep (sudo apt-get install boost), or bundle the .so along with the package lib-directory.

**Comment by sigbjorn** [comment]
Solved
