### ISSUE TITLE
calibrator.region_model.statistics.discharge mangler verdier etter kalibrering/calculate_goal_function

### ISSUE THREAD

**Issue by elialfnes** [statkraft/shyft#109]
Hvis jeg kalibrerer med tilsigsserier som ikke inneholder/er koblet til delfeltet med laveste nummer i region.yaml-fila,  så lagres det ikke verdier i calibrator.region_model.statistics.discharge.

calibrator.optimizer.calulate_goal_function beregner og returnerer målfunksjonen som forventet, dvs med fornuftig verdi.

/eli

**Comment by sigbjorn** [comment]
Finally resolved in PR #122 . Thanks for precise hints that also confirmed the type of problem
