### ISSUE TITLE
merge of PR #114 breaks example calibration notebook

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#115]
commit 7a476be9c92e26669d6dbac0b6a6f69c5c7e023d

Merging of the new routing PR #114 breaks the calibration example notebooks in config_simulator.py
`
/config_simulator.py in <listcomp>(.0)
    173         [model_params[name_map[r]].update({p: getattr(getattr(optim_param, r), p)})
    174          if name_map[r] in model_params else model_params.update(
--> 175             {name_map[r]: {p: getattr(getattr(optim_param, r), p)}}) for r, p in [nm.split('.') for nm in self.calib_param_names]]
    176         model_dict.update({'model_parameters': model_params})
    177         # Save the update parameters on disk

KeyError: 'routing'
`

A first error was no entry routing in the calibration.yaml, but adding this causes knock on problems. We need to find a way to include routing without breaking existing simulation configuration.

**Comment by sigbjorn** [comment]
it's saving the calibration parameters that was broken, undetected, later we need to require some more tests for the yaml config to  ensure we don't have to trust our memories.
