### ISSUE TITLE
ec_concat_data_repository.get_forecasts doc

### ISSUE THREAD

**Issue by runeyosh** [statkraft/shyft#154]
I'm not completely sure how to use ec_concat_data_repository.get_forecasts(self, input_source_types, fc_selection_criteria, geo_location_criteria), spesifically the fc_selection_criteria. I want to write code that runs through all new EC forecasts and shove them into SmG for each Inflow catchment. What would be the correct syntax for getting whole, singular forecasts given something like a date?

**Comment by yisak** [comment]
`import numpy as np
from shyft import api
from shyft.repository.netcdf.ec_concat_data_repository import ECConcatDataRepository
repo_params = {'epsg': 32633,
          'filename': '//energycorp/applications/OSL/Shyft_Data/shyft_data/repository/ec_data_repository_merged/ec_merged_all.nc'}
repo = ECConcatDataRepository(**repo_params) 
utc = api.Calendar()
input_source_types = ('temperature','wind_speed','relative_humidity','radiation','precipitation')
xll, yll, dx, dy, nx, ny = 266000, 6960000, 1000.0, 1000.0, 109, 80
bbox =(np.array([xll, xll+dx*nx, xll+dx*nx, xll]),
           np.array([yll, yll, yll+dy*ny, yll+dy*ny]))
geo_location_criteria = {'bbox': bbox} # if using bbox 
# geo_location_criteria = {'polygon': poly_obj} # if directly using a shapely polygon object (poly_obj)
#######################################
# To get a single forecast
#######################################
forecast_period_start = utc.time(2017,8,7,0) # the start time of the single forecast (EC00 for 2017.08.07 in this example)
forecast_period_end = forecast_period_start
#######################################
# To get all forecasts within a period
#######################################
forecast_period_start = utc.time(2017,8,3,0) # the start of the period for which you want to fetch all forecast
forecast_period_end = utc.time(2017,8,7,0) # the end of the period for which you want to fetch all forecast

period = api.UtcPeriod(forecast_period_start,forecast_period_end)
fc_selection_criteria = {'forecasts_within_period': period}
geo_ts_vector = repo.get_forecasts(input_source_types, fc_selection_criteria, geo_location_criteria)

# One alternative to using the 'forecasts_within_period' option while fetching a single forecast is the 'latest_available_forecasts' option
# fc_selection_criteria = {'latest_available_forecasts': {'number of forecasts': 1, 'forecasts_older_than': forecast_period_start}
# Another alternative which is included but not implemented yet (very easy to implement if needed) is the 'forecasts_at_reference_times' option
# This option is meant for cases where one wishes to fetch multiple forecasts at explicitely specified start_times which are irregularly spaced in time
# It can be used to fetch a single forecast by sending in only ine start time
# fc_selection_criteria = {'forecasts_at_reference_times': [forecast_period_start]}`

**Comment by yisak** [comment]
```python
import numpy as np
from shyft import api
from shyft.repository.netcdf.ec_concat_data_repository import ECConcatDataRepository
repo_params = {'epsg': 32633,
          'filename': '//energycorp/applications/OSL/Shyft_Data/shyft_data/repository/ec_data_repository_merged/ec_merged_all.nc'}
repo = ECConcatDataRepository(**repo_params) 
utc = api.Calendar()
input_source_types = ('temperature','wind_speed','relative_humidity','radiation','precipitation')
xll, yll, dx, dy, nx, ny = 266000, 6960000, 1000.0, 1000.0, 109, 80
bbox =(np.array([xll, xll+dx*nx, xll+dx*nx, xll]),
           np.array([yll, yll, yll+dy*ny, yll+dy*ny]))
geo_location_criteria = {'bbox': bbox} # if using bbox 
# geo_location_criteria = {'polygon': poly_obj} # if directly using a shapely polygon object (poly_obj)
#######################################
# To get a single forecast
#######################################
forecast_period_start = utc.time(2017,8,7,0) # the start time of the single forecast (EC00 for 2017.08.07 in this example)
forecast_period_end = forecast_period_start
#######################################
# To get all forecasts within a period
#######################################
forecast_period_start = utc.time(2017,8,3,0) # the start of the period for which you want to fetch all forecast
forecast_period_end = utc.time(2017,8,7,0) # the end of the period for which you want to fetch all forecast

period = api.UtcPeriod(forecast_period_start,forecast_period_end)
fc_selection_criteria = {'forecasts_within_period': period}
geo_ts_vector = repo.get_forecasts(input_source_types, fc_selection_criteria, geo_location_criteria)

# One alternative to using the 'forecasts_within_period' option while fetching a single forecast is the 'latest_available_forecasts' option
# fc_selection_criteria = {'latest_available_forecasts': {'number of forecasts': 1, 'forecasts_older_than': forecast_period_start}
# Another alternative which is included but not implemented yet (very easy to implement if needed) is the 'forecasts_at_reference_times' option
# This option is meant for cases where one wishes to fetch multiple forecasts at explicitely specified start_times which are irregularly spaced in time
# It can be used to fetch a single forecast by sending in only ine start time
# fc_selection_criteria = {'forecasts_at_reference_times': [forecast_period_start]}
```

**Comment by runeyosh** [comment]
Thanks! Will post further comments on Shyft Google group, as discussed!
