### ISSUE TITLE
absolute value of ts or ts-vector

### ISSUE THREAD

**Issue by sigbjorn** [statkraft/shyft#162]
# Overview

ts.abs()->ts
ts_vector.abs()->ts_vector

**Comment by yisak** [comment]
This would help accomplish, in C++, what would have been done in python like this given a TsVector tsvct and a Timeseries Ts
```python
def stack_average(tsvct , Ts):
    tsvct_new = api.TsVector()
    [tsvct_new.push_back(Ts.average(ts.time_axis)) for ts in tsvct ]
```

**Comment by sigbjorn** [comment]
To match observation ts against forecast ts-vector,

diff = ts_forecast_vector - ts_observation  # type of diff is ts_vector, time-axis of each member unique
