### ISSUE TITLE
OSP-6: Merge orchestration and orchestation2

### ISSUE THREAD

**Issue by skavhaug** [statkraft/shyft#17]

**Comment by FrancescAlted** [comment]
Any suggestion on how to bootstrap the process?  My suggestion would be to migrate existing repositories to orchestration2 (inside the shyft.orchestration2), check that all tests passes (even those using proprietary DBs) and then rename `shyft.orchestration` -> `shyft.orchestration2`.  Probably that would deserve one PR per repository that has to be migrated and a final one with the renaming (and deletion of overridden repositories).

At the same time, using Continuous Integration would be a nice tool to follow how the different tests are increasingly passing until the full migration has been done.  I will try to set some functional CI as well (in a different PR).

**Comment by sigbjorn** [comment]
OSP-6 merged, issue closed.
