### ISSUE TITLE
Best practice for Slicing TimeSeries

### ISSUE THREAD

**Issue by tobiasli** [statkraft/shyft#185]
I have a TimeSeries, and need to make a new TimeSeries as a subset of the original based on a UtcPeriod.

I could decompose the TimeSeries into value and time, do the slicing on the components and then make a new TimeSeries, but I thought there might more streamlined approach that I can't seem to find. Any tips?

**Comment by tobiasli** [comment]
```
from shyft.api import TimeSeries, TimeAxis, UtcPeriod, Calendar, TsVector
from numpy import arange, equal

ta = TimeAxis(0, 1, 20)  # 0 ... 20
value = range(20)  # 0 ... 19
ts = TimeSeries(ta, value)
slice_period = UtcPeriod(5, 12)  # 5 ... 12
expected_result = arange(5, 12)  # 5 ... 11


def match_output(method=None, expected=None, new=None):
    try:
        assert equal(expected, new.values.to_numpy()).all()
        print(f'{method} success')
    except:
        print(f'{method} failed.')

method = 'Decompose, slice, compose:'
value = ts.values.to_numpy()
time = ts.time_axis.time_points[0:-1]
new_value = value[(time >= slice_period.start) & (time < slice_period.end)]
new_ta = TimeAxis(slice_period.start, ts.time_axis.fixed_dt.delta_t, len(new_value))
new_ts = TimeSeries(new_ta, new_value)
match_output(method, expected_result, new_ts)

method = 'TimeSeries.partition_by:'
# As I read the documentation this should work, but it doesn't return what I would expect.
tsv = ts.partition_by(Calendar(), slice_period.start, slice_period.timespan(), 1, slice_period.start)
# Funfact: The above method crashes if you use kwargs instead of args in the same order. Documentation seems to be off.
new_ts = tsv[0]
match_output(method, expected_result, new_ts)

method = 'TsVector.average'
# This method seems to calculate the average integral, and will not return the same specific values as the input series.
tsv = TsVector()
tsv.append(ts)
ta_slice = TimeAxis(slice_period.start, ts.time_axis.fixed_dt.delta_t, int(slice_period.timespan()/ts.time_axis.fixed_dt.delta_t))
new_ts = tsv.average(ta_slice)[0]
match_output(method, expected_result, new_ts)
```

**Comment by sigbjorn** [comment]
Hi,

Despite your efforts here,  the background objective and definitions are not 100% clear.

A 5-min whiteboard session will help a lot carving out the specs. and then
figure out a quick & fast implementation if needed.

Br Sigbjørn

**Comment by yisak** [comment]
This can be achieved in a number of ways. For your simple example (fixed temporal resolution and slicing period which perfectly matches with the interval beginnings), this should do the job. 
```python
from shyft.api import point_interpretation_policy as ts_typ
method='one_liner:'
new_ts = TimeSeries(ts.time_axis,ts.v,point_fx=ts_typ.POINT_AVERAGE_VALUE).average(TimeAxis(slice_period.start,ts.time_axis.fixed_dt.delta_t,(slice_period.end-slice_period.start)//ts.time_axis.fixed_dt.delta_t))
match_output(method, expected_result, new_ts)
one_liner: success
```

**Comment by tobiasli** [comment]
Thanks for the replies. 

@sigbjorn : I considered walking over to you and solving this on the whiteboard, but I chose to take the discussion on Github so the information is available to anyone (and even googleable!). I think it might be a good idea to (if possible) take more of the use-case-discussions on Github instead of the office to help with information flow. Especially in cases where it might be that the user (me) is coming at an issue from the wrong angle.

**Comment by tobiasli** [comment]
Yisaks solutions works fine, along with my self having to remember to always add point_fx to TimeSeries (which is now mandatory). Thanks for the feedback.
