### ISSUE TITLE
statkraft gis service

### ISSUE THREAD

**Issue by yisak** [statkraft/shyft#194]
Even though this is Statkraft specific, I post it here until Statkraft specific repositories are moved to 'internal'.

The PREPROD URL for the GIS service does not work

This URL fails->"http://oslwvagi001q:6080/arcgis/rest/services/SHyFT/SHyFT/MapServer"
While the https variant works
"https://pregisserver.statkraft.com:6443/arcgis/rest/services/SHyFT/SHyFT/MapServer"

For PROD both variants work
"http://oslwvagi002p:6080/arcgis/rest/services/SHyFT/SHyFT/MapServer"
"https://gisserver.statkraft.com:6443/arcgis/rest/services/SHyFT/SHyFT/MapServer"

The one used in shyft's gis_region_model_repository is the http variant. Two questions:
-Why is the PREPROD http variant failing? Is it because of server name?
-Should we switch to this URL template or is there some advantage of using the http varoant?
url_template = "https://{name}:{port}/arcgis/rest/services/SHyFT/" + sub_service + "/MapServer/{}/query"
prod_name->"gisserver.statkraft.com"
preprod_name->"pregisserver.statkraft.com"
port-> 6443
Yisak

**Comment by sigbjorn** [comment]
Yes, we can go on doing that, and verify if it works, -then just publish changes.
