### ISSUE TITLE
Precipitation on unregulated (natural) lakes and regulated lakes (reservoir)

### ISSUE THREAD

**Issue by yisak** [statkraft/shyft#206]
Is precipitation falling directly on both unregulated (natural) lakes and regulated lakes (reservoir) added to immediate response? Shouldn't this be done only for precipitation falling on reservoirs? The inflow to the reservoirs is calculated from water level (pressure sensors in the reservoir) while this is not the case for discharge measured at a gauging station downstream a natural lake.

https://github.com/statkraft/shyft/blob/2cf7173bdbbf6a8135403e985fe98dc3bd633b6b/core/pt_gs_k.h#L312

**Comment by sigbjorn** [comment]
Yes, as it states, for now. In addition discussions about the snow-covered lake/reservoir effects, covered in earlier issues/PR.
This is entirely up to you to decide, - the implementation and comment just refects no clear decision at that time.

**Comment by sigbjorn** [comment]
We do change this along with glacier.

Lake is routed through kirchner/soil if no routing, otherwise direct from cell to routing points.
Reservoir is always direct
glacier is direct_response 0..1 routed, as parameter

**Comment by sigbjorn** [comment]
As of #212 , we have a changed strategy for this, including flexible glacier response. Further plans for lake, direct to routing if available will be considered when we get more experience with routing.
