### ISSUE TITLE
GeoTsRepository Interface discussion

### ISSUE THREAD

**Issue by eriktjotta** [statkraft/shyft#233]
Hi all!

The Interface for `GeoTsRepository` has the following public function:

```
def get_timeseries(self, input_source_types, utc_period, geo_location_criteria=None):
def get_forecast(self, input_source_types, utc_period, t_c, geo_location_criteria=None):
def get_forecast_ensemble(self, input_source_types, utc_period,
                          t_c, geo_location_criteria=None):
```

The arome/ec_concat_data_repositories contain a public function that generalizes `get_forecast`:

```
def get_forecasts(self, input_source_types, fc_selection_criteria, geo_location_criteria):
```
The concat_data_repository extends this to ensemble forecasts, hence if we follow along the current lines we need to also introduce:

`get_forecast_ensembles`
`get_time_series_ensemble`

and would have to update the Interface the include the following six public function:

`get_timeseries`
`get_time_series_ensemble`
`get_forecast`
`get_forecast_ensemble`
`get_forecasts`
`get_forecast_ensembles`

To me this seems like overkill and potentially very confusing, hence I would like to propose that we simplifying this to only two public functions:

```
def get_timeseries(self, input_source_types, utc_period, geo_location_criteria=None):
def get_forecasts(self, input_source_types, fc_selection_criteria, geo_location_criteria):
```
where the return from the `get_timeseries` is always a list of ensemble members (with just one member if deterministic forecast), 

the return `get_forecasts` is a list of list of ensemble members and the following `fc_selections criteria` are supported:

```
fc_selection_criteria: dict
    Following fc_selection_criteria are supported:
        * 'forecast within period': utc_period
            get forecast created within period
        * 'forecasts_with_start_within_period': utc_period
            get forecast with nb_to_drop-horizon within period
        * 'forecasts_that_cover_period': utc period
            get forecast where (nb_to_drop, lead_intervals) cover period
        *  'latest_available_forecasts': (number_of_forecast, time_stamp)
            get latest number_of_forecast older than time_stamp
        * 'forecasts_at_reference_times': list
            get latest forecast for list of time_stamps
```

This would cover all of the above six cases and would provide us with an tidy Interface which would be easy to extend with more `fc_selection_criteria` at a later stage.

Alternatively we could land on:

```
def get_timeseries(self, input_source_types, utc_period, geo_location_criteria=None):
def get_forecast(self, input_source_types, utc_period, t_c, geo_location_criteria):
def get_forecasts(self, input_source_types, fc_selection_criteria, geo_location_criteria):

```
where `get_forecast` avoids the list of list stuff and just returns a list of ensemble members since just one forecast is asked for.

Any opinions?

Best,
Erik

**Comment by jfburkhart** [comment]
Great suggestion again from @eriktjotta ! Simplifying the interface makes sense. If we are to do this, it will require refactoring existing repositories, but this will be easier now than later.

Before embarking on the refactoring, we should think a bit about the generalization and keep in mind our known uses cases (arome, ec, senorge (soon), gfs).

**Comment by jfburkhart** [comment]
If we refactor, I also suggest a change from `geo_location_criteria` (redundant as geo implies location) to `geo_selection_criteria` which is more explicit regarding the intent of the variable.

**Comment by jfburkhart** [comment]
Per discussions:

Six methods is not too much for an interface. It is most important to keep in mind the main ‘driving force’ behind the interfaces are the **promises** they need to cover.

SIH: An optimal interface should have 4-10 methods implemented. Not more, not less. (it doesn’t make sense to have too few, and it gets crowded if you have too many). Nice with the six that we propose now -- easy to document on one A4 paper, clearly.

We concluded with the following interfaces:


```
get_timeseries - as defined

get_timeseries_ensemble - returns timeseries as all ensemble members, selection of individual ensemble members should happen later. This will always return all available ensembles from the dataset.

get_forecast - returns singular forecast, point is we don’t know the length, this is distinct from get_timeseries

get_forecast_collection - accepts fc_selection_criteria see #234

get_forecast_ensemble - returns a single forecast ensemble -- all types, precip, temp, etc. will have the same number of ensembles

get_forecast_ensemble_collection - accepts fc_selection_criteria, returns a collection of forecast ensembles

```



fc_selection_criteria should be a class. Not a dictionary… this is more robust, will enable more help from IDEs, benefits from pycharm, etc. See #234

argument `geo_location_criteria` will be changed to `polygon` to be more specific (or `selection_polygon`?). This can be None, in which case no spatial subsetting will occur.

Create a new argument that is unique_id, but is this only relevant for timeseries? We need still to discuss whether unique id is removed altogether from geotsrepository, for now it will be a new keyword. Has to be mentioned. Simply:

```
unique_id=None

If not unique_id:
	raise NotImplementedError
```

Two issues not concluded:

1. do we introduce, and if so where, `unique_id`? Only in `ts_repository` or also in `geo_ts_repository`?

2. Do the ensemble methods have an argument to return a subset of ensembles? If so what type? Proposal: a list, with indices (zero-indexed). Or None, meaning all (default).

**Comment by eriktjotta** [comment]
Issue 2:

> Do the ensemble methods have an argument to return a subset of ensembles? If so what type? Proposal: a list, with indices (zero-indexed). Or None, meaning all (default).

**Comment by jfburkhart** [comment]
@eriktjotta possibly, we could think about a `selection_criteria` class (rather than `fc_selection_criteria` per #234 ). If we have a generic `selection_criteria` class, could this not also handle the issue regarding which ensemble(s) to return? And in fact, while thinking about it, couldn't it simply have an attribute `polygon`, which if set to `None` would be equivalent to not passing a `geo_location_criteria`?

I know this potentially violates @sigbjorn 's points about not allowing too much complexity, but it seems it could be a solution here.

Our methods would then accept this simple class:

```
 @abstractmethod
    def get_timeseries(self, input_source_types, utc_period, selection_criteria=None):
```

And lastly, this could, in fact, simplify the need for so many different methods, if we just rely on a well defined generic `selection_criteria` class.

@sigbjorn  Thoughts? Pros, Cons?

**Comment by eriktjotta** [comment]
Then I would rather see that all the other selection stuff we have at class level is put into the fc_selection_criteria:

```
       nb_pads: int, optional 
           Extend forecast horizon with nb_pads lead times by replicating last values 
       nb_fc_to_drop: int, optional 
           Index of first lead time to read 
       nb_lead_intervals: int, optional 
           Number of lead time intervals to read 
       fc_periodicity: int, optional 
            Periodicity of forecast to read  padding: float, optional 
       use_filled_values: bool 
           Use forecast with filled valued if True 
```
Also, can whoever had the idea of putting fc_selection_criteria into a class put up some simple example code to illustrate the idea? That would make the discussion much more concrete.

I really hope we can land this issue swiftly and move on.

**Comment by jfburkhart** [comment]
See #234. I would like to hear from @sigbjorn regarding all these optional criteria. To be, so long as the function is well documented this could lead to a clear approach for users. But perhaps there are strong arguments from the test/maintenance perspective that would argue otherwise.

**Comment by eriktjotta** [comment]
Keeping it simple is probably wise.

Can we close this issue with the conclusion on the six methods (which is what the original post asked for) and leave the discussion on selection criteria to #234? Untill that has been resolved we leave as `fc_selection_criteria `as a dict.
