### ISSUE TITLE
Shyft class instantiation with numpy float or int

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#235]
There is some inconsistencies in some of the Shyft `api` classes, in that some will accept a `numpy.float`:

`gp = api.GeoPoint( x, y, z ) # where x, y, z are numpy floats is no problem`

whereas in other cases it fails:

`geo_cell_data = api.GeoCellData(gp, cell_area, cid, rad_fx, land_cover_frac)`

In this case, `cell_area` and `cid` cannot be numpy types. More details are provided here:
https://groups.google.com/forum/#!topic/shyft/t0QyC3eBHXg

This is confusing for a user to have to cast sometimes to pure python and sometimes not. The expected behavior would be that the `api` classes should be able to accept numpy floats and ints. I suggest changing the instantiation of `api` classes to generally accept numpy types.

**Comment by sigbjorn** [comment]
We rely on standard features provided by the framework (boost::python), we are using.
If we find elegant solutions that ease use, meaning a few lines of code, we for sure put them in place to make things easier. This could be possible, and we can have a look at it.

about mixing int/float (in general):
  int-> float|double : is usually ok (possible overflow)
  float|double ->int  :  usually not ok, users should not expect this to work

**Comment by jfburkhart** [comment]
Sorry if my description was not clear. I do not intend to describe the issue of mixing float/int, but rather `np.float`/`float` where the latter is a native python type. And the same may be the case for `np.int`/`int`.

In the example linked to, you can see that when I cast the `np.float` and the `np.int` using `float()` and `int()`, the `GeoCellData` instantiated without problem.

**Comment by jfburkhart** [comment]
Per discussions, the resolution:

This behavior results from the boost::python interface. We use `double` and `int` in the instantiation of objects. In some cases, for example `GeoPoint`, a `np.int` will be accepted by boost::python and cast to a double internally. However, `np.int32` will not be. Where a `double` is expected, a `np.float32` will fail, as will `np.float64`.

We won't fix this, but may investigate whether a custom double type may be defined and applied universally which is more 'accepting' (within limits).
