### ISSUE TITLE
NetCDF4/NumPy errors in test suite

### ISSUE THREAD

**Issue by FrancescAlted** [statkraft/shyft#25]
During my work on TravisCI config files, and after making all dependencies right, the test suite is still failing in a couple of tests of the Python test suite:

```
======================================================================

ERROR: Simple regression test of arome data respository.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/FrancescAlted/shyft/test/python/TestOrchestration.py", line 393, in test_read_all_times

    ar1 = AromeDataRepository(pth1, EPSG, bounding_box, period)

  File "/home/travis/build/FrancescAlted/shyft/shyft/repository/arome_data_repository.py", line 207, in __init__

    raw_data[data_field] = data[data_slice]

  File "netCDF4/_netCDF4.pyx", line 3318, in netCDF4._netCDF4.Variable.__getitem__ (netCDF4/_netCDF4.c:30994)

  File "/home/travis/miniconda/envs/shyft_env/lib/python2.7/site-packages/netCDF4/utils.py", line 230, in _StartCountStride

    if ea.max()+1 > elen:

  File "/home/travis/miniconda/envs/shyft_env/lib/python2.7/site-packages/numpy/core/_methods.py", line 26, in _amax

    return umr_maximum(a, axis, None, out, keepdims)

ValueError: zero-size array to reduction operation maximum which has no identity
```

You can see more details (like versions and others) in the [TravisCI log file](https://travis-ci.org/FrancescAlted/shyft/builds/86997072).

**Comment by skavhaug** [comment]
Hi,

could this be a data issue?

Ola Skavhaug, PhD
Founder, Expert Analytics AS

**Comment by FrancescAlted** [comment]
I don't think so, as that works in my laptop.  It is probably something related with latest versions of dependencies (maybe NumPy 1.10?).

**Comment by skavhaug** [comment]
I see.

It works on my Ubuntu box with NumPy 1.10 and netCDF4 1.2.1.

O

Ola Skavhaug, PhD
Founder, Expert Analytics AS

**Comment by FrancescAlted** [comment]
I am able to reproduce this by using the conda netcdf4 package (1.1.9 as of this writing).  By using the latest for PyPI I am getting this:

```
.................EE.............................
======================================================================
ERROR: Simple regression test of arome data respository.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/faltet/uio/shyft-FA/test/python/TestOrchestration.py", line 393, in test_read_all_times
    ar1 = AromeDataRepository(pth1, EPSG, bounding_box, period)
  File "/home/faltet/uio/shyft-FA/shyft/repository/arome_data_repository.py", line 207, in __init__
    raw_data[data_field] = data[data_slice]
  File "netCDF4/_netCDF4.pyx", line 3537, in netCDF4._netCDF4.Variable.__getitem__ (netCDF4/_netCDF4.c:35562)
  File "/home/faltet/miniconda/lib/python2.7/site-packages/netCDF4/utils.py", line 361, in _StartCountStride
    start[...,i] = np.apply_along_axis(lambda x: e*x, i, np.ones(sdim[:-1]))
  File "/home/faltet/miniconda/lib/python2.7/site-packages/numpy/lib/shape_base.py", line 91, in apply_along_axis
    res = func1d(arr[tuple(i.tolist())], *args, **kwargs)
IndexError: index 0 is out of bounds for axis 3 with size 0
```

It crashes in the same place, but the error seems a bit more informational.

**Comment by FrancescAlted** [comment]
My current versions for dependencies are dlib 18.17, armadillo 6.100.0 (although I checked with 5.400.3, 5.600.2 and 6.100.1, all reproducing the error) and boost 1.59.0.  I would say that it should be some of them,  What are your versions?

**Comment by skavhaug** [comment]
Pretty sure this is a data issue, really. The slice is empty. Are you sure
you're using the exact same data files (netCDF)?

I've changed the slicing logic in OSP-6, after encountering a similar
problem earlier. Generally, using full rank boolean index arrays is more
robust than indexing with a sub-index array. I think is faster as well.

O

Ola Skavhaug, PhD
Founder, Expert Analytics AS

**Comment by FrancescAlted** [comment]
Well, I am using the master branch at https://github.com/statkraft/shyft-data.git, so probably the fault is there.  Apparently you are running on a different data repo?  If so, could you please fix master?

**Comment by skavhaug** [comment]
It's fixed in OSP-6, and the issue is minor. I suggest we wait for the
OSP-6 merge. The only time the issue occurs, I think, is when slicing out
all the data from the netcdf dataset, which one would generally not do due
to the size of it. When the slice index array is of full rank, numpy does
some funky stuff. Hence the switch to boolean, full-rank index arrays.

Alternatively, one could make the test-dataset a bit bigger, avoiding the
bbox to surround the area completely.

Ola

**Comment by skavhaug** [comment]
How's this issue doing after merging OSP-6 into master?

**Comment by FrancescAlted** [comment]
I will have a look as soon as I can.  It does work for you I suppose.

**Comment by skavhaug** [comment]
Yes, it works fine. It was kind of related to the fact that numpy slices do
not behave like netCDF slices (the latter is independent in each dimension).

Anyways - please let me now if we still have trouble and I'll see what I
can do.

**Comment by FrancescAlted** [comment]
Ok.  So I will close this now and will reopen if necessary.

**Comment by FrancescAlted** [comment]
Works for me.
