### ISSUE TITLE
Clean up references to SHYFT_DEPENDENCIES_DIR

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#263]
There are some issues regarding the `SHYFT_DEPENDENCIES_DIR` and how it is referenced. In many of the build / configuration scripts it is hard coded as a default, and the env_var seems not to be respected. 

In other cases, a different env_var than we assume is referenced (e.g. `SHYFT_DEPENDENCIES` vs. `SHYFT_DEPENDENCIES_DIR`:
https://github.com/statkraft/shyft/blob/386d18ebc37c3d7342270acc399a74d2ed7b25a1/setup.py#L74

It is respected within the `CMakeLists.txt` file:

```
# The dependencies directory
if(DEFINED ENV{SHYFT_DEPENDENCIES_DIR})
  set(SHYFT_DEPENDENCIES_DIR $ENV{SHYFT_DEPENDENCIES_DIR})
else()
  set(SHYFT_DEPENDENCIES_DIR "${PROJECT_SOURCE_DIR}/../shyft_dependencies")
endif()

```

But in the `build_api_cmake.sh` script the `LD_LIBRARY_PATH` variable does not reference the dependencies variable (which may exist):
```
export LD_LIBRARY_PATH=${WORKSPACE}/shyft_dependencies/lib:$LD_LIBRARY_PATH
```
Perhaps most critically, the `build_support/build_dependencies.sh` script fails to respect the environment variable, and potentially overrides it:
```
export SHYFT_DEPENDENCIES_DIR=${WORKSPACE}/shyft_dependencies
```
The proper approach should be to test for this variable in the `setup.py` file, and set it one time there. However, some of the other scripts do get run manually, so we may need to include tests in each of the files as well.

**Comment by jfburkhart** [comment]
I will address the linux build. But I won't touch any of the Windows specific portions. I will leave that to @sigbjorn ... or whomever else dares!

**Comment by sigbjorn** [comment]
Now aligned, hopefully working. Regarding build-support, we now have several build-engines using jenkins. The usual pattern is to build core and test, then api (install inplace), run tests, then build wheel, conda-dist etc. based on the files/libraries actually tested.
