### ISSUE TITLE
Repository interfaces.py cleanup

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#265]
The `interfaces.py` module is central for defining the requirements of different repositories.

It should be kept clean and minimal, but there are several classes defined within for which I find no usage. These include:

 * `TsRepository`
 * `GeoLocationRepository`
 * `TimeseriesStore`

Is there a reason we should preserve these or were they early conceptualizations which we no longer require?

**Comment by yisak** [comment]
All of these interface classes are used for repositories in internal  and
in addition TsRepository is used for repository.netcdf.cf_ts_repository.
CFTsRepository.

**Comment by jfburkhart** [comment]
Strange, because I don't find a reference to them in PyCharm... Okay, I will check deeper. What do you know about `GeoTsRepositoryCollection` ? Is it in use anywhere?

**Comment by yisak** [comment]
Is is not a part of interfaces. It is used for the nea-Nidelva example, in
some AROME and orchestration tests + in
shyft.orchestration.configuration.yaml_configs.YAMLSimConfig. It is what
makes it possible to pack multiple repos and make them apparat as one repo
for the orchestration.

**Comment by sigbjorn** [comment]
Regarding cleanup, we could also put some more focus into upgrading to python 3.6+ with type-annotations. This will make it easier for people from the coding perspective (pycharm&al), -and we can drop out the type-specification from the doc-strings, as they are now available through the type-annotation. 

Regarding interfaces related to time-series, I think the dtss will take that role, and currently provides url-syntax for reading/storing time-series. That interface is 'hard' and precise (boost/python over c++), and well proven through various large scale projects.

The next interface for dtss would/could be to add the geo-dimension, - allowing us to move the classical repositories as 'collectors' for the geo-location aware dtss-backend.  

This  would solve performance challenges that for now is solved using clever netcdf chunksize along with reducing and collecting relevant forecast into one single netcdf file (thanks to Yisak for resolving those performance issues using pure python approach!)
