### ISSUE TITLE
CFDataRepository, __init__ file change

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#275]
At some point we changed the initialization of the CFDataRepository in a way which breaks all the yaml configured simulations:

https://github.com/statkraft/shyft/commit/b63d05fa8199fc9081da4bcb67fa0050784af779#diff-3529236e7879055e5d728e0d09ac463bR18

This clearly took too long to be noticed... we should consider better testing of notebooks. @yisak did you make this change?

**Comment by yisak** [comment]
Yes i did + updated tests.

**Comment by jfburkhart** [comment]
Okay, but this is breaking for the notebooks. We need to make sure the changes are propagated there as well.

**Comment by jfburkhart** [comment]
The complication arose as the updated .yaml configuration files are in the `shyft/tests/netcdf` directory, whereas the notebooks have their own set of configuration yaml files. It would make sense to have only one version, but at the same time it does complicate referencing (e.g. notebooks need to make a reference to the shyft directory). If the shyft directory is not explicitly checked out, for example if someone installed with the sigbjorn channel, then they would need to point to the shyft package... for example:

```
# set up configuration using *.yaml configuration files
# here is the *.yaml file that configures the simulation:
example_configs = os.path.join(shyft.__path__[0], 'tests/netcdf')
config_file_path = os.path.abspath(os.path.join(example_configs,"neanidelva_simulation.yaml"))
    
# and here we pass it to the configurator, together with the name of the region 
# stated in the simulation.yaml file (here: "neanidelva") which we would like to run
cfg = YAMLSimConfig(config_file_path, "neanidelva")
```

This works, but is a bit cumbersome, as we want people to be able to "look at" the yaml files, and I'm afraid newcomers would find it a bit peculiar to dig into a `python/lib` directory and explore a package to find the yaml files.

Maybe they should be in `shyft-data` and both the test suite and notebooks refer to them there.
Other suggestions?

**Comment by jfburkhart** [comment]
Will be address in #280
