### ISSUE TITLE
Cells to numpy, numpy to cells

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#279]
In order to avoid looping in python (required currently to achieve the following), several cases would be of interest regarding extraction and injection of data to/from Shyft to be implemented as C++ core functionality.

As a user we would like to:
Case 1 inject pre-interpolated results **to** cells by passing a numpy array (time, ncells) **to** Shyft and have it 'fill cells' with the pre-interpolated data.
For example:
`` region_model.fill_interpolated_values``

Case 2 extract interpolated values from cells directly to a numpy array (time, ncells)
`` region_model.get_interpolated_values``

Case 3 extract response results/states **from** cells directly to a numpy array (time, ncells)
`` region_model.get_result_values``
This exists on some level as ``region_model.statistics`` but the desire is to have more direct access to the raw results at cell/time level.

**Comment by sigbjorn** [comment]
Comments and ideas:

General:

**ts and numpy**: ts.values could be np.array directly, this is easy to implement, somewhat more work to actually get through regarding test&change.  The effect is that we get rid of .to_numpy() (only).

I discourage flattening time-series and expressions to numpy, except in the cases where we are on the perimeter/interface level, that  is input/output to other algorithms, that consumes/produces numpy, or algorithms we not yet have implemented as time-series algorithms.


Specific:
Case 1:

 We need a robust way to map the correct time-series to cell, by identity or geo-proximity.
   .. and then also detect failure detection/misses etc. 

     geo-proximity: user specify 'nearest' and max-distance (using z-scale to discriminate heights)
                             if to large distance raise exception, leave model untouched.
                             Should the user also specify catchment id ?
                             **Btw**: We get this for free already,  using n-neigbours=1 and IDW?

     cell-identity(x,y,z,area): 'exact' match required.  
                             Should user-supplied data match all cells(or specified catchment ids).
                             What happens to not-matched time-series or cells ?

     other-failures: times, and data-values does not match (complete) time-axis
                            
Case 2:
I think the intention with the region_model.statistics was to provide direct access over catchments, or set of such. It provides either the sum/average, or vector of values for specified time/time-axis index reference. Ref. test-code, that also illustrates how to access interpolated forcing variables.

Should we work more on the documentation and examples(notebooks?) to illustrate the use ?
Are there minor adjustments we could do ?

Case 3:
The direct access to cell inputs, result and state is provided very directly pr. cell.
 It is provided so directly that we actually is reading/writing the cell-time-series values.
 If it's for reading bulk-content of cells, into a ts-vector, this is quite easy to provide, 
  it will then be a copy of the time-series, into a  TsVector. 
  From the TsVector we have already some functionality when it comes to flatten 
   & slice out values to numpy arrays.
    Maybe we could extend and improve these parts ?

**Comment by sigbjorn** [comment]
Added example using IDW to join two geo temperature sources, with possible different geo-properties, that have non-overlapping time-ranges in just one go using standard provided functions already in shyft.

The source code is checked in for illustration, but here is how it looks:
```python
    def test_idw_respects_sources_time_axis_range(self):
        """
        Test case for the following scenario:

        You have two sets of geo-located temperature (or other forcing variables),
        where the source-grid is slightly changed between the sets.
        This can happen if EC changes elevation/projection model, or you would like to merge two EC data-sets with
         slightly different geo-/elevation model in one go.

        The first set of data is valid for
           TimeAxis ta_1 ( t0, dt, n)
        and the second set of data is valid for the next timesteps after the first one:
           TimeAxis ta_2 (t0+dt*n,dt,m)

        Let's say you want 2 neighbours, for the interpolation.

        But since shyft idw determines the candidates based on distance *before* doing the interpolation loop,
        we have to tell it to use 2x2 neighbours, - although we know that due to the non-overlapping data
        this will effectively be just 2 neighbours for each time-step.
        .. and in this case exactly what we want to achieve.

        """
        #
        # Arrange the test
        idw_p = api.IDWTemperatureParameter()
        idw_p.max_distance = 200000
        idw_p.max_members = 2*2  # we have two data-sets, and would like shyft interpolation to keep a list of
        fx_arome_1 = lambda z: [10 + x/100.0 for x in range(self.n)]
        arome_grid_1 = self._create_geo_temperature_grid(self.nx, self.ny, self.dx_arome, fx_arome_1)
        fx_arome_2 = lambda z: [20 + x/100.0 for x in range(self.n)]
        arome_grid_2 = self._create_geo_temperature_grid(self.nx, self.ny, self.dx_arome, fx_arome_2)
        dest_grid_points = self._create_geo_point_grid(self.mnx, self.mny, self.dx_model)

        ta = api.TimeAxis(self.t, self.d, self.n)  # the api.idw_temperature requires
        ta_1 = api.TimeAxis(self.t, self.d, self.n//2)
        ta_2 = api.TimeAxis(ta_1.total_period().end, self.d, self.n//2)
        #  now ensure that the geo-ts in grid_1 have a limited time-axis that ends where the grid_2 starts
        #  If you read forecasts from a repository, concatenated, you should consider if this
        #  is needed or not, recall that repositories are required to return *at least* enough data to
        #  match the request period.
        for gts in arome_grid_1:
            gts.ts = gts.ts.average(ta_1)  # average effectively clip the values to ta_a1
        for gts in arome_grid_2:
            gts.ts = gts.ts.average(ta_2)  # similar for ta_2 and grid_2, they now cover disjunct part of time-axis

        arome_grid_1.extend(arome_grid_2)  # just concatenate the geo ts-vector, it work as list as for all other xxxVector types
        dest_grid = api.idw_temperature(arome_grid_1, dest_grid_points, ta.fixed_dt, idw_p)  # .fixed_dt -> TimeAxisFixedDeltaT type
        self.assertIsNotNone(dest_grid)
        self.assertAlmostEqual(dest_grid[0].ts(ta_1.time(0)), 10.0)  # first step should be 10.0, selecting from the grid_1
        self.assertAlmostEqual(dest_grid[0].ts(ta_2.time(0)), 20.0 + (self.n//2)/100.0)  # first step  second time-axis, should show grid_2 value
        self.assertAlmostEqual(dest_grid[0].ts(ta_2.time(0)-1), 10.0 + (-1+self.n//2)/100.0) # just before that step, it should still be grid_1 value
```

**Comment by yisak** [comment]
The following two aspects mentioned above definitely make the task much easier:
- all time-intervals outside the defined time-axis for the input sources will be interpreted as NaN and there is, therefore, no need of padding (extending) with extra NaNs to cover the full period
- for number of duplicate points (nb_duplicate)  and desired number of neighbors (nb_real_neighbors),  the number of neighbors passed to IDW interpolation = nb_duplicate *  nb_real_neighbors

**Comment by yisak** [comment]
But why would one want to mix same source type from different databases in
the same region model?For sources coming from different database one should
use one region model for each database. For example, if u have temperaturer
coming from EC and station observations, u cannot mix them as they have
totally different bias and spatial support (reprensentativity). However,
mixing different source types can be OK: using temperature from station
observation and radiation from EC for example.

For doing mixing of same source type one should downscale, bias-correct and
project the different  sources to a common reference first and easily use
one region model. This is what GridPP and QM are for. So a gridded data
from EC and Point observation from stadions should first be COMBINED
outside. And this combination is a topic of research on its own and not
something we can work around by just sending all source to IDW and
interpolate :-)

**Comment by felixmatt** [comment]
Absolutely true. I was trying to think of situations where the approach doesn't hold. While from a technical point of view this is possible, it doesn't make much sense from a physical point of view.

**Comment by felixmatt** [comment]
What I don't really like so far is, that depending on the time period fetched from a data repository, the configuration of IDW needs to be updated. Do you think it would make sense to have the information about the number of duplications directly accessible from the source vector? E.g. source_vector.nb_duplicate. Then IDW could calculate the number of nearest neighbours itself, nb_interpolation = nb_duplicate * nb_real_neighbors, where nb_real_neighbors comes from the IDW parameter, and nb_duplicate from the source vector.

**Comment by yisak** [comment]
Actually I do not think that yon need to do any configuration updating or even think about how many duplicates you have. And here is why: 
IDW in shyft first identifies the number of neighbors to each target point by using only those neighbors which are within the max_distance (parameter of IDW). It reduces the number of neighbors to max_nb_neighbors if the number of neighbors within max_distance exceed max_nb_neighbors. It is the max_distance (radius) parameter which is the most important in IDW. max_nb_neighbors is there for very specific needs where the number of neighbors has to be limited for some special reason. So for the case with the duplicates, the same max_distance you would have used if you had no duplicates can be used. The max_nb_neighbors can be chosen a bit larger so that no important neighbors are dropped. But remember that this larger max_nb_neighbors will make the IDW work IDENTICALLY both for the case with and without duplicates. Lets say you want neighbors within 5 km and max_nb_neighbors=4. If the actual number of neighbors to a target point (without duplicates) is 2 then IDW will pick 2 neighbors for the case without duplicate and 4 neighbors for the case with duplicates. But while screening the neighbors for the case with duplicates it will drop the two duplicates because of NaN values and will effectively use 2 neighbors (exactly the same 2 points the IDW for the case without duplicates would have used). So you will get the same behavior for both cases without having to specify difference configuration for each.
