### ISSUE TITLE
proposal: move shyft/shyft/tests/netcdf yaml config files to shyft-data

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#280]
The yaml config files reference data located in the `shyft-data` repository which are required for testing. The `shyft-doc` repository also uses the same yaml files, but they need to be explicitly copied into the `shyft-doc` repository.

Since the yaml files themselves refer to the `shyft-data` repository, and therefore the `shyft-data` repository is required for the tests to successfully complete, we should just keep the .yaml files together with their netcdf counterparts in the `shyft-data` repository and the tests can refer to the `shyftdata` environment variable.

In `shyft-doc` we could then refer to the same. This would be helpful for new users as it would assure the `shyft-doc` yaml files are concurrent / aligned with test coverage.

**Comment by sigbjorn** [comment]
Yes, go ahead, - I encourage using relative paths where-ever possible, and SHYFT_DATA only to override this.

**Comment by jfburkhart** [comment]
Fixed currently in the senorge branch.
