### ISSUE TITLE
OSP-2: Automatic build

### ISSUE THREAD

**Issue by skavhaug** [statkraft/shyft#3]
# Integrate with automatic build system

Evaluate and set up automatic build. Important topics:
 * Multi platform
 * Pre-built binaries

**Comment by FrancescAlted** [comment]
Do we have some available machine that can act as the automatic build system?

**Comment by sigbjorn** [comment]
Francesc PR cmake  with travis is now part of shyft. ( I do have a aws ubuntu I could upgrade to host the travis builds).

windows build: - in statkraft we can setup one using teamcity (for internal use, but we could push binaries out).
another approach is to see if latest mingw  gcc 64 is able to build some shyft on windows.
 Codeblocks (c++ dev for free), works ok for windows with gcc as well.

**Comment by jfburkhart** [comment]
I will close this now that cmake and Travis CI is complete, and open a new issue for Windows cmake
