### ISSUE TITLE
Datadir

### ISSUE THREAD

**Issue by skavhaug** [statkraft/shyft#31]
Statkraft has testdata in more locations than shyftdata_dir.

**Comment by FrancescAlted** [comment]
shyftdata_dir is really meant to act as a way to avoid specifying absolute paths for all datafiles. So maybe you can use absolute paths for your use case?  Or you prefer another solution?

**Comment by skavhaug** [comment]
This is very statkraft specific, really, and we use absolute paths in the tests as properties. My experience is that since shyftdata_dir is the "official" and public data location, only that data should reside there. So when we need another datadir internally, we simply add them in the tests (as properties on the test class, really).

**Comment by sigbjorn** [comment]
Statkraft specific tests and data would only work in statkraft environment. We have established a statkraft local repository that can handle these cases. Most important that  sk-specific tests are skipped automatically outside sk-environments.
