### ISSUE TITLE
Mass balance violation in hbv_stack, pt_ss_k, and pt_hs_k

### ISSUE THREAD

**Issue by felixmatt** [statkraft/shyft#315]
It looks like there are bugs in the hbv and the pt_ss/hs_k stacks that violate the mass balance when running the model at time steps different from 3600 s. The reason for this is that precipitation input time series are by definition given in mm/h,
`api.PrecipitationSource?`
`Docstring: geo located precipitation [mm/h]`,
independently from the simulation time step, but the stacks do not account for the time step dependent total amount of precipitation.

In the pt_gs_k stack, this is done correctly and the total precipitation per time step is calculated by scaling precipitation with the timestep-hours in the [gamma_snow routine](https://github.com/statkraft/shyft/blob/master/core/gamma_snow.h#L300).

This step is missing in both, skaugen_snow and hbv_snow, which has consequences for the hbv_stack, pt_ss_k, and pt_hs_k.

A simple example demonstrating the following inconsistency can be seen in the Figures. The model is run at 1h and 24 h time steps using artificial data. Note that SWE is differing by a factor of about 24 between gamma_snow on the one hand, and skaugen/hbv_snow on the other hand, when using 24h time step. No inconsistency is shown at a time stepping of 1h.
![1h png](https://user-images.githubusercontent.com/14838574/43526802-5846ffe6-95a5-11e8-8d4d-866d87caaad4.PNG)
![24h png](https://user-images.githubusercontent.com/14838574/43526815-5f9e7ada-95a5-11e8-82fd-69c96e9d2292.PNG)

The fix can be done either on the the stack level, or has to be done in each of the routines that take precipitation as input.

**Comment by felixmatt** [comment]
source code to reproduce figures:
[api_model.zip](https://github.com/statkraft/shyft/files/2249863/api_model.zip)

**Comment by sigbjorn** [comment]
Thanks, I provide a branch with the fix, plus new package at conda channel sigbjorn.
