### ISSUE TITLE
api.GeoCellData.set_catchment_id() does not set a provided integer

### ISSUE THREAD

**Issue by felixmatt** [statkraft/shyft#317]
cell.geo.set_catchment_id() does not set a provided integer, but simply returns catchment_id when no argument is passed. I would expect the method to take an integer as argument. Am I misunderstanding this?

example:
`from shyft import api`
`geo_cell_data = api.GeoCellData()`
`geo_cell_data.set_catchment_id(1) # raises error`
`geo_cell_data.set_catchment_id() # returns currently set (default) catchment id`

**Comment by sigbjorn** [comment]
We fix, this, including doc.
The set_method is questionable, since it can only be used before we create a model.
I put a warning in there as long as we keep the method.
