### ISSUE TITLE
api.pt_gs_k.PTGSKModel needs catchment_parameters; documentation tells different

### ISSUE THREAD

**Issue by felixmatt** [statkraft/shyft#318]
According to documentation, one should be able to construct api.pt_gs_k.PTGSKModel from cell_vector and region_parameter only:
Docstring:   
`__init__( (object)arg1, (HbvCellAllVector)cells, (HbvParameter)region_param) -> None :`
`creates a model from cells and region model parameters`

However, trying this raises an error. Passing additional catchment_parameters works.

Either documentation or source code needs to be adapted. Same accounts for the other model types (PTSSKModel, PTHSKModel, HbvModel).

Example:

`model_type = api.pt_gs_k.PTGSKModel`
`x,y,z = 0,0,0`
`area = 1000000`
`cid = 1`
`mid_point = api.GeoPoint(x,y,z)`
`geo_cell_data = api.GeoCellData(mid_point, area, cid)`

`cell = model_type.cell_t()`
`cell.geo = geo_cell_data`
`cell_vector = model_type.cell_t.vector_t()`
`cell_vector.append(cell)`

`region_parameter = model_type.parameter_t()`

`# catchment parameters`
`catchment_parameters = model_type.parameter_t.map_t()`
`catchment_parameters[1] = region_parameter`

`# works fine`
`region_model = model_type(cell_vector, region_parameter, catchment_parameters)`

`# raises error, but shouldn't according to documentation`
`region_model = model_type(cell_vector, region_parameter)`

`# workaround`
`region_model = model_type(cell_vector, region_parameter, catchment_parameters)`
`region_model.remove_catchment_parameter(1)`

**Comment by sigbjorn** [comment]
I think we remove that constructor, it's not used(obviousely obsolete), and was replaced by easy to use GeoCellDataVector, that is also tested, and documented.
