### ISSUE TITLE
rm.create_opt_model_clone() causes seg.fault

### ISSUE THREAD

**Issue by sigbjorn** [statkraft/shyft#320]
The create_opt_model_clone(..) method purpose is to ease construction of a fast/optimial model-clone of a full-model (often with region-env step projection to cell all set.

It turns out that unless you re-run the opt-model interpolation step,(defeating the purpose of this function), this causes the use of the model in optimization context to crash.

**Comment by felixmatt** [comment]
Closing issue as PR #321 is solving the issue.
