### ISSUE TITLE
Interpolation parameters not respected during calibration

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#323]
A fairly significant bug was discovered during calibration of a mountainous region with large elevation gradients. Results from simulation using the calibrated parameter provided significantly different results from the calibration for the same period. See the [discusssion](https://groups.google.com/forum/#!topic/shyft/6OUzJFm7IQ4)

During the debug session we discovered that, essentially, it is the YamlCalibConfig class that does not update the model with the interpolation parameters provided in the interpolation.yaml file. This **could** be due to the fact that these parameters are set only once at line 162 in `simulator.py`:

https://github.com/statkraft/shyft/blob/aa91ec246efe78131ed1b4cfcc7730545a52ac71/shyft/orchestration/simulator.py#L162

During calibration, this line is never reached.

Furthermore, it is felt by @felixmatt and me that it would be better to move this line to the `__init__` or somewhere earlier that would be called such that once you have typed:

```
cfg = YAMLSimConfig(config_file_path, "neanidelva")
simulator = ConfigSimulator(cfg)
```
or 
```
cfg = YAMLCalibConfig(config_file_path, "neanidelva")
calib = ConfigCalibrator(cfg)
```
Your `simulator` or `calib` objects would be fully configured, such that you could immediately use `simulator.region_model.run_cells()`, for example.

**Comment by felixmatt** [comment]
Fixed in PR #324. Closing issue.
