### ISSUE TITLE
Time doesnt define __round__ method

### ISSUE THREAD

**Issue by bjarkithorh** [statkraft/shyft#331]
Hei, I get an error when I try to fetch data via the Bokeh apps.
```
ERROR:bokeh.server.protocol.server_handler:error handling message Message 'PATCH-DOC' (revision 1): TypeError("type time doesn't define __round__ method",)
```

**Comment by sigbjorn** [comment]
Yes it does, - your version is outdated, please update, ref. test in shyft:

   def test_time_round(self):
        self.assertAlmostEqual(round(api.time(3.2)), 3.0)
        self.assertAlmostEqual(round(api.time(-3.7)), -4.0)
