### ISSUE TITLE
ForecastSelectionCriteria (possibly other classes) must either accept time or get input cast to int

### ISSUE THREAD

**Issue by runeyosh** [statkraft/shyft#336]
ForecastSelectionCriteria (utils) checks if input is int, which it is not when called from todays ConcatDataRepository, and will not accept input as time object.

Either FSC must be rewritten to accept time, or places where the class is used must cast the input to int.

I can do the code changes if we agree on where and what to change

**Comment by yisak** [comment]
A robust approach would be to cast what is passed in as a variable representing time, t,  to api.time(t).  This process itself will raise a runtime error if a successful conversion could not be made. In this way  multiple representations of time (int, float and iso 8601s string) can be handled/accepted. We can either catch the Runtime Error and pass it over to raise ForecastSelectionCriteriaError or simply let it fail with the Runtime Error. @sigbjorn what do you think?
```python
t='not_int-not-float_not-valid-iso-string'
t=api.time(t)
RuntimeError: Needs format 'YYYY-MM-DDThh:mm:ssZ': got not_int-not-float_not-valid-iso-string
```

**Comment by sigbjorn** [comment]
Hi, just pass on the runtime-error, we can change the error text in shyft, so that it reads, 'not possible to convert '...' to time, you have to provide time as seconds (int or float), or iso 8604-string, like ...'
