### ISSUE TITLE
TravisCI should be activated for upstream SHYFT repo

### ISSUE THREAD

**Issue by FrancescAlted** [statkraft/shyft#35]
Right now, TravisCI is configured in my fork to my account: https://travis-ci.org/FrancescAlted/shyft, but it would be nice if a shyft account can be activated for testing upstream shyft repo.  Unfortunately, I don't have privileges for doing that, but here are some [easy instructions](https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo) for someone with master privileges.

After that, update the build status line in README.md by replacing 'FrancescAlted' by 'shyft'.  Also, for getting a nice picture of the build status, see: http://docs.travis-ci.com/user/status-images/

**Comment by jfburkhart** [comment]
Fixed now, builds are passing!

**Comment by FrancescAlted** [comment]
Sweet!
