### ISSUE TITLE
read the docs and search

### ISSUE THREAD

**Issue by sigbjorn** [statkraft/shyft#350]
# Overview

There seems to be an issue with the current read-the-docs,
that inhibit searching through the api.

When producing sphinx locally into shyft-doc, this works as expected.
Search for TimeSeries, and you get all the hits you need to start working.

Steps to reproduce:
1. https://shyft.readthedocs.io/en/latest/index.html
2. fill in TimeSeries, search..

Current version just hang, giving no  matches.

Browsing to the index, however, shows there is a lot of doc's in there.

**Comment by jfburkhart** [comment]
I confirm that it works on a local build and the failure at rtd. I assume it has something to do with integrations. I will look into this.

**Comment by jfburkhart** [comment]
Fixed now with [#5](https://github.com/statkraft/shyft-doc/pull/5)
