### ISSUE TITLE
change catchment id integer type to int64

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#360]
There are some cases where the integer type may exceed regular int:

```
In [17]: cid = 17060308144731

In [18]: sa.GeoCellData(sa.GeoPoint(23., 23., 23.), 23., cid)
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-18-c43c162bfcb8> in <module>()
----> 1 sa.GeoCellData(sa.GeoPoint(23., 23., 23.), 23., cid)

OverflowError: bad numeric conversion: positive overflow

In [19]: cid = np.int64(cid)

In [20]: sa.GeoCellData(sa.GeoPoint(23., 23., 23.), 23., cid)
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-20-c43c162bfcb8> in <module>()
----> 1 sa.GeoCellData(sa.GeoPoint(23., 23., 23.), 23., cid)

ArgumentError: Python argument types in
    GeoCellData.__init__(GeoCellData, GeoPoint, float, numpy.int64)
did not match C++ signature:
    __init__(_object* self, shyft::core::geo_point mid_point, double area, int catchment_id)
    __init__(_object* self, shyft::core::geo_point mid_point, double area, int catchment_id, double radiation_slope_factor)
    __init__(_object* self, shyft::core::geo_point mid_point, double area, int catchment_id, double radiation_slope_factor, shyft::core::land_type_fractions land_type_fractions)
    __init__(_object* self, shyft::core::geo_point mid_point, double area, int catchment_id, double radiation_slope_factor, shyft::core::land_type_fractions land_type_fractions, shyft::core::routing_info routing_info)
    __init__(_object*)

In [21]:
```

Is it possible to update the `api.GeoCellData` to accept int64 for the catchment id value?

**Comment by sigbjorn** [comment]
I guess you are on the windows platform ?
linux do have 64bit, win ms is 32bit ints, in that case it's platform specific.
windows supports 32bits ints, linux 64.
So on windows, 32bits ints, sets the limitation.

We could typedef catchment_id to  int64_t, and try to work on that all over (or at least for the code-paths leading to catchment-id. But that would some work to support win32 only

**Comment by sigbjorn** [comment]
ahh, reading your error message once more, you are passing np.int64, you should do int(), and your done. (at least if you are on linux).

**Comment by sigbjorn** [comment]
hmm. no, - seems like it goes via int32 on linux as well. so int64_t will solve it (was the original intention, 64bits) Using sa.Int64Vector() illustrates that int64 easily handles the number.

**Comment by sigbjorn** [comment]
After looking some more into it, int64_t, applied wherever catchment_id is in play would work. It also require the cids that usually is an IntVector (and 64bit on linux) to be int64_t. Maybe flipping IntVector to alias for Int64Vector could work out. It takes some effort though to ensure we get rid of the win-platform issues regarding this.
