### ISSUE TITLE
dtss cacheing

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#366]
A question about dtss... not sure whether I'm understanding proper usage. I'm trying to use it as an 'ephemeral' memory cache (no disk usage). Below is a test that I believe outlines my expectations:

I am not getting the expected behavior necessarily in the final `for  url, ts in zip(self.gh.ts_urls, tsv)` loop:

     def test_store_cache(self):

        # setup data to be calculated
        utc = Calendar()
        d = deltahours(1)
        d24 = deltahours(24)
        n = 240
        n24 = 10
        t = utc.time(2016, 1, 1)
        ta = TimeAxis(t, d, n)
        ta24 = TimeAxis(t, d24, n24)
        n_ts = 100
        percentile_list = IntVector([0, 35, 50, 65, 100])
        tsv = TsVector()
        store_tsv = TsVector()  # something we store at server side
        for i in range(n_ts):
            pts = TimeSeries(ta, np.linspace(start=0, stop=1.0, num=ta.size()),
                             point_fx.POINT_AVERAGE_VALUE)
            tsv.append(float(1 + i / 10) * pts)
            self.gh.ts_urls.append(self.gh.ts_url(uuid.uuid1()))
            store_tsv.append(TimeSeries(self.gh.ts_urls[i], pts))  # generate a bound pts to store
            period = pts.total_period()
        self.gh.dtc.store_ts(store_tsv)

        self.assertIsInstance(self.gh.ts_urls, list)

        tsv = TsVector([TimeSeries(ts) for ts in self.gh.ts_urls])
        tsv = self.gh.dtc.evaluate(tsv, period )

        self.assertIsInstance(tsv, TsVector)
        for url, ts in zip(self.gh.ts_urls, tsv):
            print(ts.ts_id)
            print(url)
            self.assertEqual(ts.ts_id(), url)
            self.assertIsInstance(ts, TimeSeries)
            self.assertEqual(ts.total_period(), period)
`

**Comment by jfburkhart** [comment]
`self.gh` is a class that provides `DtsClient` as the `.dtc` attribute. `.ts_url` is a mapping function to generate a string url.

**Comment by sigbjorn** [comment]
The tsv after the evaluate will have the resolved time-series, 
  ts_id() is a method, not property.
.evaluate will deliver same order and count out as passed in.
