### ISSUE TITLE
cmake for Windows

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#37]
With @FrancescAlted 's #33 we have cmake for Ubuntu. Next step is to create a setup for other systems, with a priority presumably for Windows for Statkraft. This will have to be by @statkraft/owners

**Comment by FrancescAlted** [comment]
Just wanted to point out that the CMake support is general for Linux (or at least any reasonably recent Linux distro), and not only for Ubuntu.  The Mac OSX support should be relatively easy to implement. And Windows would require more effort (but possible indeed).

**Comment by sigbjorn** [comment]
I think that in Statkraft we  will use MIAD standard tools, including build system, -  when needed.
Currently we maintain ms vs 2015 solution and project for this, and we have a path-relative setup simliar to linux. We keep on with this approach for now.

cmake currently just works for the tested environment, and after trying it on fedora, arch linux, I still feel there is a lot of improvement needed for cmake to appear as a clear main alternative for c++-mode of work.

Currently I can't se there is a benefit to a goal like "we should be able to build shyft for any compiler/library etc.",

I have been rather specific to that we are going to follow the 'head' libraries for boost, gcc etc. and absolutely put zero effort into supporting, or even try to support older versions at this stage.

For the open source, and possible future:

I have already a working codeblock, pycharm, gcc (mingw-w64) setup working for windows, basically by just following the build-setup on wiki (but with some 'windows' specific steps).
It follow standard download, setup,compile for the dependencies, 
Once they are in place, codeblock build works, debug works, pyton works etc.etc.

I will do some work on this, and publish it to the wiki, -then there might be a chance that the cmake for shyft stuff also could work. Cmake it has to be configured for gcc, and that was actually one of the obstacles when I was compiling armadillo etc. so cmake on windows is not a walk in the park ;-)

**Comment by jfburkhart** [comment]
Thanks. Sounds like a good forward direction. I'm still quite keen on cmake as I feel it will be community-wide beneficial, at least for linux users.

**Comment by sigbjorn** [comment]
open another issue for automated builds.
