### ISSUE TITLE
Dtss.evaluate with result-clipping period

### ISSUE THREAD

**Issue by sigbjorn** [statkraft/shyft#390]
When calling dtss.evalute(tsv, terminal_read_period..)->tsvector, the results could be larger than terminal_read_period.
In some cases, we would like to limit the result within a specified period.

Extend the evaluate function with one extra result_clip_period,default=none, argument that allows passing this period in to the server.

* Make sure that the existing protocols works as before (extra message type, at the end of the enum list

* Validate the result_clip_period (dtss_client, client side, before it is passed to server)

* Imlement clip_to_period(tsv,period)->tsv. (time_series_dd.cpp)

* On the dtss server, just before returning result, check if clip-period active, then call the clip_to_period(..) prior to passing result back.

* Update unit-tests, c++

* Update python tests dtss, with example

* Optional update notebook example. (shyft-doc/notebooks).

**Comment by tobiasli** [comment]
Wow! This is a potentially great enhancement. What is the type of the `result_clip_period` argument? Is it a TimeAxis?

Using this for normal or other large-timeaxis calculations would be very elegant.
