### ISSUE TITLE
How to extract a single TimeSeries from a ConcatDataRepository?

### ISSUE THREAD

**Issue by tobiasli** [statkraft/shyft#396]
I am trying to fetch the single timeseries from a gridded forecast that overlaps a point in space. The point is covered by the netcdf-file in question. The following code illustrates that the ConcatDataRepository treats the gridded values as points and not as an actual grid.

```python
from shyft.api import Calendar, UtcPeriod
from shyft.repository.netcdf.concat_data_repository import ConcatDataRepository, ConcatDataRepositoryError
from shapely.geometry import Point

args = {'epsg': "32633",
'filename': "[insert path to merged calibration arome netcdf]",
'nb_lead_intervals_to_drop': 0,
'padding': 0.,
'nb_lead_intervals': None,
'fc_periodicity': 1,
'fc_delay': 0,
'ensemble_member': 0,
'use_filled_values': False}

repo = ConcatDataRepository(**args)

variable = 'temperature'
# Location that I know is covered by forecast: (aprx middle of Vik):
x = '31967'
y = '6820259'
cal = Calendar()
read_period = UtcPeriod(cal.time(2018, 1, 1), cal.time(2018, 2, 1))
point = Point(float(x), float(y)).buffer(10)

print('Grids are continuous, so a small area should intuitively yield a single timeseries:')
try:
    dictionary = repo.get_timeseries([variable], read_period, point.buffer(10))
    print(f'Success! Got {len(dictionary[variable])} timeseries.')
except ConcatDataRepositoryError as e:
    print(e)

print('We try with 3000 m diameter (grid resolution 2500 m, so at least one should hit):')
try:
    dictionary = repo.get_timeseries([variable], read_period, point.buffer(1500))
    print(f'Success! Got {len(dictionary[variable])} timeseries.')
except ConcatDataRepositoryError as e:
    print(e)
print('Done.')

>>> Grids are continuous, so a small area should intuitively yield a single forecast:
>>> No points in dataset which are within the geo_location_criteria polygon.
>>> We try with 3000 m diameter (grid resolution 2500 m, so at least one should hit):
>>> Success! Got 2 timeseries.
>>> Done.
```

What would be a clever way of extracting a single timeseries from the ConcatDataRepository? Or does this need a completely different approach?

**Comment by tobiasli** [comment]
Calling @yisak and @runeyosh

**Comment by runeyosh** [comment]
evnt @eriktjotta , kjenner ikke concat så godt selv

**Comment by yisak** [comment]
> What would be a clever way of extracting a single timeseries from the ConcatDataRepository? Or does this need a completely different approach?

To do a two-step-extraction: first fetch points as you showed above and extract the one which is closest to the desired point.

**Comment by tobiasli** [comment]
Ok. That's fair. Does the ConcatDataRepository represent grids as midpoints or lowerleftcorners? I assume midpoints, but ask for the sake of documentation.

**Comment by yisak** [comment]
For AROME and EC products the coordinates represent pixel-center

**Comment by sigbjorn** [comment]
In stead of a point, getting the closure, and then use shyft interpolation to transfer the surrounding points the values to your point. In addition, you could even use the gridpp and kalman-filter to adjust for daily temperature-changes/bias (in case of temperature).

**Comment by tobiasli** [comment]
@sigbjorn That's a good idea. What would be the simplest function calls for geographical interpolation?

**Comment by yisak** [comment]
How can interpolation be a solution here? Maybe I have misunderstood but I thought the intention of @tobiasli was, given a point,  to extract the timeseries for the grid cell which overlaps with (encloses) this point without manipulating the original timeseries for the grid cell. Interpolation will not take into account the form or shape of the grid cell.

**Comment by tobiasli** [comment]
The intention can be either, depending on what the user wants. Initially, the user wants "something", so it doesn't really matter for the sake of the test, as long as we know which. And picking forecast number 1 from the set of forecasts returned by the geo_location_criteria felt a bit random.

**Comment by yisak** [comment]
>  And picking forecast number 1 from the set of forecasts returned by the geo_location_criteria felt a bit random.

What do u mean exactly by 'picking forecast number 1 from the set of forecasts'? Extraction of the timeseries for the grid cell which overlaps with (encloses) the desired point is by no means random.

**Comment by tobiasli** [comment]
I know it's not random, but it is arbitrary and has undocumented consequences (as in it "felt random"). It will probably always return the (for example) north-eastern-most data point within geo_location_criteria depending on the netcdf file definition and which points get parsed first.

But this is really beside the point (pun intended). You have given me the information I need, really.
@yisak Knowing that the datasets we use are pixel center and that ConcatDataRepository treats everything as points is fine. Then I just need to find the closes GeoTimeSeries to my initial coordinates.

@sigbjorn Having the choise of interpolation may be relevant at a later date.
