### ISSUE TITLE
ConcatDataRepository: delta_t metadata without performing data read.

### ISSUE THREAD

**Issue by tobiasli** [statkraft/shyft#397]
I'm making a metadata query for a ConcatDataRepository to match the expected return of `DtsServer.find_cb()`. So I'm trying to validate inputs without performing an actual data read, and get metadata for the resulting timeseries also without performing an actual data query.

Validation:
Calling `ConcatDataRepository._validate_input()` seems to be the method for the job, and doc states that it should validate the `geo_location_criteria `as well. But the code doesn't touch the geo_location_criteria. The workaround is to call `_limit_1D` outside the scope of the `ConcatDataRepository` 

Metadata:
For metadata I've figured out point_fx and UtcPeriod, but delta_t seems to only be calculated deep within the `get_timeseries()` (and related) methods.

Is there a way to find delta_t without reading arbitrary data?

**Comment by yisak** [comment]
As it is now not there is no method to get delta_t . And the reasons for this is that delta_t is not a fixed variable and it could also vary from variable to variable.

**Comment by tobiasli** [comment]
Ok. The repo has time points in repo.time. So I figured, as an estimation, I could extract the mode of delta_t across all timesteps and assume this as delta_t. . If these are not homogeoneous across variables in the file, what does repo.time represent?

**Comment by yisak** [comment]
Repo.time represents the starting times of each forecast. So the delta_t u will Get here represents the forecast issuing interval and not the temporal resolution of the timeseries returned.

**Comment by tobiasli** [comment]
Ah, ok. Could that time-information be added to the parameter documentation?

Is there any way of getting the time-axis information via the dataset or similar? I can't find anything via perusing the netcdf.Dataset-parameters, so i guess not.

**Comment by tobiasli** [comment]
I've got the information I need for the time being!

`ConcatDataRepository.time[0]` gives me the start of the first forecast, so this is my metadata start time. The metadata end time is `ConcatDataRepository.time[-1] + forecast_length' but i don't know `forecast_length`. So I'll just leave that field blank.

Thanks!
