### ISSUE TITLE
Convolve TS binding is dependent on the convolve policy

### ISSUE THREAD

**Issue by eistaa** [statkraft/shyft#420]
When using `convolve_policy.CENTER` then the `convolve_w` time-series method only work in a bound context. This is not a problem with the `FORWARD` or `BACKWARD` policies.

The following code demonstrates the problem. The `test_bind_info` function is copied directly from the existing test code and works. While the `test_bind_info_center` test function fails with the message `"TimeSeries, or expression unbound, please bind sym-ts before use."`.

```
def test_bind_info(self):
    ts = TimeSeries("a")
    w = DoubleVector.from_numpy([0.05, 0.15, 0.6, 0.15, 0.05])
    tsd = ts.convolve_w(w, convolve_policy.USE_NEAREST | convolve_policy.BACKWARD)
    bi = tsd.find_ts_bind_info()
    self.assertEqual(len(bi), 1)

def test_bind_info_center(self):
    ts = TimeSeries("a")
    w = DoubleVector.from_numpy([0.05, 0.15, 0.6, 0.15, 0.05])
    tsd = ts.convolve_w(w, convolve_policy.USE_NEAREST | convolve_policy.CENTER)
    bi = tsd.find_ts_bind_info()
    self.assertEqual(len(bi), 1)
```

-----

Tested at commit `a76f7c5`, currently the tip of master.

**Comment by sigbjorn** [comment]
cause: new code try to validate user input parameters during construction, that will fail for unbound ts. solution -> defer checks that require source ts until evaluate time.
