### ISSUE TITLE
Define / Create Demo Case

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#46]
@yisak and @jfburkhart will define a demonstration case from openly available data sets. Aspects to include:
   - freely available data (e.g. the test case may not necessarily need to distribute data)
   - multi-catchment
   - point stations
   - distributed input data (ECMWF reanalysis?)
   - reasonable size simulation (e.g. can run on standard laptop)

**Comment by sigbjorn** [comment]
The notebook published on shyft-doc for nea-nidelv meets this requirements, -or can easily be extended to even more cases.
