### ISSUE TITLE
OSP-3: Skaugen Snow improvements

### ISSUE THREAD

**Issue by skavhaug** [statkraft/shyft#5]
Various minor improvements of the Skaugen Snow routine - make sure to merge before doing anything serious with the pt_ss_k stack in master.

**Comment by jfburkhart** [comment]
@skavhaug where are we with this? I feel like this issue got left hanging somehow... it's done, no?

**Comment by skavhaug** [comment]
Skaugen works, and this is a branch for improvements. I have not opened a
PR, and I have some things I plan to implement in it. So we should leave it
as is. Generally speaking, I think we should allow branches to exist for
quite long time periods, but perhaps we should discuss this.

**Comment by sigbjorn** [comment]
I think there will be situations like this, - where it makes a lot sense to have a long living branch.
It allows us to see work in progress, and to contribute to it.

**Comment by jfburkhart** [comment]
I'm okay with a long-living branch, but let's avoid a situation like OSP-6 where it introduces a large number of changes and we seek an intensive review following the merge. We need to be all engaged with the PR.

**Comment by jfburkhart** [comment]
(and I acknowledge that I should have followed more closely the changes)

**Comment by skavhaug** [comment]
I agree that big PRs are very difficult to deal with. Optimally, no PR
should contain more than 600-700 LOC, imo. The delta for the Skaugen Snow
routine will be quite small, however.

Ola Skavhaug, PhD
Founder, Expert Analytics AS
