### ISSUE TITLE
ipython help vs ?

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#70]
When in ipython, help displays different information from the '?' notation:

`​
    help(api.PriestleyTaylorResponse)

```
Help on class PriestleyTaylorResponse in module shyft.api._api:

class PriestleyTaylorResponse(Boost.Python.instance)
 |  Method resolution order:
 |      PriestleyTaylorResponse
 |      Boost.Python.instance
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(...)
 |      __init__( (object)arg1) -> None :
 |      
 |          C++ signature :
 |              void __init__(_object*)
 |  
 |  __reduce__ = <unnamed Boost.Python function>(...)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  pot_evapotranspiration
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  __instance_size__ = 24
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from Boost.Python.instance:
 |  
 |  __dict__
 |  
 |  __weakref__
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from Boost.Python.instance:
 |  
 |  __new__ = <built-in method __new__ of Boost.Python.class object>
 |      T.__new__(S, ...) -> a new object with type S, a subtype of T
```

`

whereas if you use the '?' or even '??' you get less information:

`

```
api.PriestleyTaylorResponse?

Docstring:      <no docstring>
Init docstring:
__init__( (object)arg1) -> None :

    C++ signature :
        void __init__(_object*)
File:           ~/hycamp/software/shyft_workspace/shyft/shyft/api/_api.so
Type:           class
```

`

**Comment by sigbjorn** [comment]
There are real differences in the standard python help() and ipython/jypyter ?? systems.
We would like to provide the relevant doc to the finger-tips of the users, but we have to work within the supported frame works of python/ipython.

What we can easily do is to ensure that there is doc-strings for all classes methods etc.
and maybe also use some standards (numpy doc is currently choosen for the python parts of shyft).

Then just hope that the remaining work is just configuration of the ipython/jupyter consoles.

If anybody do have a good tip how to write 
a) doc-string at class level (giving away the concepts)
b) properties (of the class, usually useful along with a)
c) methods, and their arguments
.. that can provide more information (compared to just providing numpy-style docs), that would be helpful.

**Comment by jfburkhart** [comment]
Major improvements with boost:python doc exposure, and continual improvements are being realized. Specifically #238 will be helpful. Closing as this is covered mostly now.
