### ISSUE TITLE
DefaultStateRepository instantiation seems circular

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#71]
This is something for @yisak , and maybe this is related to the reason @sigbjorn wasn't too happy about config files, but the following blocks of code seem a bit circular:

```
# Once we have all the configuration in place (read in from the .yaml files)
# we can start to do the simulation. Here we use the ConfigSimulator class 
# to initialize a simulator-object. Shyft has several ways to achieve this
# but the .yaml configs are convenient to use at first

simulator = ConfigSimulator(cfg)

# Now the simulator is ready to run! You can explore this object with tab
# completion. As an example, you can see here how to get the number of cells
# in the region that was set up. This is used later for extracting the data, and we'll
# need it in the construction of the state repository

n_cells = simulator.region_model.size()

# We need to instantiate a state_repos repository from the DefaultStateRepository class
# this will provide a container for the simulation states during the model run

state_repos = DefaultStateRepository(simulator.region_model.__class__, n_cells)
```

There are a couple of issues here. First `simulator.region_model.__class__` should not be exposed to users. Can't we just pass the `simulator.region_model`?

Second, the whole thing feels a little circular. We're getting the `n_cells` from the `simulator` and we're getting `region_model.__class__` from the `simulator`. Why can't we just pass the `DefaultStateRepository` the `simulator`?

Maybe this is all related to the use of configs, in which case we should make a light wrapper around `DefaultStateRepository`, say that just takes a `simulator` as an argument.

This code is from one of the demo notebooks, by the way...

**Comment by yisak** [comment]
This usage of the state repo is a copy paste from the examples when config based orchestration was not used. The way to do it now is to just specify the state repo in the config file the same way a source repo is sepcified.

**Comment by jfburkhart** [comment]
Okay, maybe you could clean up the shyft-doc/notebook I just checked in... it might be a bit dated. You can see it at c52d36f

**Comment by jfburkhart** [comment]
This issue is mostly resolved with new implementations of orchestration. Notebooks are being rewritten to follow a pure `api` approach.
