### ISSUE TITLE
snow parameter names for PTSSK and PTHSK

### ISSUE THREAD

**Issue by yisak** [statkraft/shyft#75]
The parameter names of the snow routines for model stacks PTHSK and PTSSK do not follow the convention of using initials of the snow routine name as in 'gs' for the case of the GammaSnow routine in PTGSK. 'Snow' is used insted of 'ss' for PTSSK and 'hs' for PTHSK. Seems to be the reusult of using the string 'snow' in the function 'get_name'  in \shyft\core\pt_ss_k.h and \shyft\core\pt_hs_k.h
```python
In[50]: from shyft.api import pt_ss_k
In[51]: ps=pt_ss_k.PTSSKParameter()
In[52]: [ps.get_name(i) for i in range(ps.size())]
Out[52]: 
['kirchner.c1',
 'kirchner.c2',
 'kirchner.c3',
 'ae.ae_scale_factor',
 'snow.alpha_0',
 'snow.d_range',
 'snow.unit_size',
 'snow.max_water_fraction',
 'snow.tx',
 'snow.cx',
 'snow.ts',
 'snow.cfr',
 'p_corr.scale_factor',
 'pt.albedo',
 'pt.alpha']
```

**Comment by sigbjorn** [comment]
Fixed now!
